### ISSUE TITLE
Add support for Fedora 33

### ISSUE THREAD

**Issue by x390** [vilhelmprytz/pterodactyl-installer#124]
Not officially supported by pterodactyl though I don't see an issue since docker recently added support for cgroups V2.

**Comment by Linux123123** [comment]
It is already hard to maintain support for Ubuntu, Debian and CentOS. Our mission is to support all pterodactyl supported OS's. Also Fedora is not a frequently used server distro so I don't see Pterodactyl supporting it any time soon.

**Comment by vilhelmprytz** [comment]
You could modify the script to think that Fedora 33 is actually CentOS 8 and see if it works out of the box. I don't think I have any plans on supporting Fedora. While the CentOS support is not yet decided on (because of the "only rolling release" decision), this script will always try to support all versions listed as supported by the Pterodactyl team (see [this page](https://pterodactyl.io/panel/1.0/getting_started.html#picking-a-server-os)). Closing, for now, let me know if this changes.
