### ISSUE TITLE
Wings: Docker Conflicting Packages

### ISSUE THREAD

**Issue by sansloader** [vilhelmprytz/pterodactyl-installer#125]
**Describe the bug**
Docker can't be installed due to conflicting packages: `buildah` and `podman`.
You can see error [here](https://textuploader.com/1e8ru).

**To Reproduce**
This happens on a _minimal_ installation of CentOS Stream 8 with both the [BaseOS ](https://mirrors.prometeus.net/centos/8-stream/BaseOS/x86_64/os/)and the [AppStream ](https://mirrors.prometeus.net/centos/8-stream/AppStream/x86_64/os/) packages.
I haven't tried on other OS but I think it's a package-related issue.

**Expected behaviour**
It should install Docker correctly without prompting any errors.

 **OS**: CentOS Stream 8
 **Installation**: Wings

**Additional context**
- To fix _(imhu)_ remove the conflicting packages before installing docker:
`dnf remove buildah podman`
`dnf install -y docker-ce docker-ce-cli containerd.io --nobest`

- or allow the installation to erease them:
`dnf install -y docker-ce docker-ce-cli containerd.io --nobest --allowerasing`

- or make sure to **not** install the AppStream packages (where buildah and podman are):
Pterodactyl [says specifically](https://pterodactyl.io/panel/1.0/getting_started.html#picking-a-server-os) that  "_All required packages are part of the base repos._" when installing CentOS 8 but the AppStream packages sneak in if you are not careful, you need to double check and toggle them off.
I think that adding an extra layer of control (like the previous points) won't harm.

**Comment by Linux123123** [comment]
Hi and thanks for reporting this bug.

We don't really support CentOS 8 stream, but I think we could add  `--allowerasing` anyway. @vilhelmprytz What do you think?

**Comment by vilhelmprytz** [comment]
Thanks for the bug report. As @Linux123123 mentioned, CentOS 8 stream has never been "actively supported" by this script but I believe I tested the script on both stream and non-stream when I wrote the CentOS 8 support a while back. The main goal of this script is to support whatever distributions are supported by the Pterodactyl team. I can't find any official statement from the Pterodactyl team regarding CentOS 8 stream and non-stream, do you know whether it is supposed to be supported or not? Either way, the script definitely has to be improved so that it can detect whether the system is stream or not since it right now assumes that both are just CentOS 8.

**Comment by vilhelmprytz** [comment]
Anything new about this? Is this still a bug if you use CentOS 8 stream?

**Comment by Linux123123** [comment]
It's EOL, so I think we can disregard this issue.
