### ISSUE TITLE
Pterodactyl 0.7 Install error.

### ISSUE THREAD

**Issue by Alex-idk** [vilhelmprytz/pterodactyl-installer#184]
https://pastebin.com/1nYgAdaz

I don't know if this is just a error with my machine or the script.

Ubuntu 20.04.2 LTS x86_64

**Comment by Linux123123** [comment]
@vilhelmprytz Recently updated the composer version on the legacy script, so that might have stopped it from working.

https://github.com/vilhelmprytz/pterodactyl-installer/commit/7e03097405d8c3e677ed37f5f11c5b926e3462c4

There is not that much you can do except, to git clone the repo and revert that commit and run the legacy script locally.

**Comment by Alex-idk** [comment]
I just tried that and It didn't work

**Comment by Linux123123** [comment]
Then you are going need to wait, til we fix this, as 0.7 is not our main priority.

**Comment by Alex-idk** [comment]
I have found my problem, composer needed a update. And it all works now.

Maybe add composer update in the script.

**Comment by vilhelmprytz** [comment]
All the warnings in the pastebin you sent initially contains warnings about your PHP version (8.x.x) being newer than supported by the dependencies. Did you manually install PHP before using the script?

**Comment by vilhelmprytz** [comment]
I just tried the legacy 0.7.x panel on Ubuntu 20.04. It is supposed to install PHP 7.4, which it does. You must have had PHP 8 installed before somehow? I don't think the script is broken, but feel free to reopen the issue if this is not the case! :slightly_smiling_face: Closing.
