### ISSUE TITLE
SSL: Certbot saying congrats and installer saying failed

### ISSUE THREAD

**Issue by Alex-idk** [vilhelmprytz/pterodactyl-installer#268]
**To Reproduce**
Steps to reproduce the behaviour:
Run the panel installer using ssl 

**Screenshots**
![image](https://user-images.githubusercontent.com/76760149/144731416-55a948d9-08af-4d89-8523-2df70ddd294a.png)

**OS**
 - OS: Ubuntu 20.04
 - Installation: panel

**Comment by Alex-idk** [comment]
And the paths are wrong in Nginx config.

**Comment by Linux123123** [comment]
Please provide full logs
```
cat /var/log/pterodactyl-installer.log | nc termbin.com 9999
```

**Comment by Roblox-Studio** [comment]
The ssl is failed for me

**Comment by Alex-idk** [comment]
> Please provide full logs
> 
> ```
> cat /var/log/pterodactyl-installer.log | nc termbin.com 9999
> ```

https://termbin.com/hfbh

**Comment by Alex-idk** [comment]
Also the ssl key path needs to be changed from /etc/ssl to /etc/letsencrypt/keys/

**Comment by Linux123123** [comment]
No you choose to assume ssl. That was because for some reason your certbot command returned a non successful exit code.

**Comment by vilhelmprytz** [comment]
@Alex-idk It seems to me like you ran the script several times on the same machine without resetting, is this correct?

The script does not only evaluate success based upon exit code from the certbot command, but it also checks if `/etc/letsencrypt/live/$FQDN/` exists or not.

https://github.com/vilhelmprytz/pterodactyl-installer/blob/master/install-panel.sh#L787

Since the script had been run and certbot had already tried to issue a certificate, it instead placed the cert in `/etc/letsencrypt/live/$FQDN-0001/` which is why the script said "failure".

Since we discourage running the script several times, I don't think this would occur if running on a clean system installation.

**Comment by Alex-idk** [comment]
@vilhelmprytz Sorry for late reply, after holding my up arrow for a long time I did run it again on the same system after using @Linux123123 's uninstall script to remove previous installation.
