### ISSUE TITLE
Debian installation fails due to missing sudo package

### ISSUE THREAD

**Issue by theraw** [VilhelmPrytz/pterodactyl-installer#53]
Most of debians come without `sudo` installed, so your script fails,

I suggest to add on your script `apt-get install sudo -y` or else script fails.

normally when you say "you must execute this script as root" there is no reason why you should include "sudo" on script.

**Comment by VilhelmPrytz** [comment]
Since you did not fill out the default information: is this the daemon or panel script?

Panel script does not use `sudo` for Debian, perhaps there are some I left out for the daemon script.

**Comment by theraw** [comment]
panel installation went well,

daemon failed like `docker ps` says docker not found

**Comment by VilhelmPrytz** [comment]
It looks like [line 212](https://github.com/VilhelmPrytz/pterodactyl-installer/blob/master/install-daemon.sh#L212) and [line 206](https://github.com/VilhelmPrytz/pterodactyl-installer/blob/master/install-daemon.sh#L206) have this problem. Would you like to remove the `sudo` from these two lines and send them in as a pull request?

**Comment by theraw** [comment]
i think it's better to install it

**Comment by VilhelmPrytz** [comment]
As you mentioned, it's really quite unnecessary to use `sudo` at all since the script itself requires `root` before it even begins running. I'd say it's more clean to remove the `sudo` commands but I am happy to rethink that if you know there are any other particular reasons to keep it or where it is useful in other cases?

**Comment by theraw** [comment]
yeah no and idk,

i'll have to check out everything script executes in order to answer that

by installing it its like a quick fix it can be required in other cases since some ppl use `sudo ...` and don't check at the begin if is root or not example some official pterodactyl docs include `sudo` in their `how-to`  `https://pterodactyl.io/panel/0.7/getting_started.html#queue-listeners`

**Comment by VilhelmPrytz** [comment]
Well, the script requires you to be logged in as `root` before it even executes so the `sudo` is redundant. The Pterodactyl project documentation can refer to `sudo` since each command is executed by the user separately. If anything goes wrong they can just rerun that specific command. With the script it runs everything in one go regardless of previous output, so the commands has to be correct.
