### ISSUE TITLE
apt-transport-https

### ISSUE THREAD

**Issue by danielnaaman** [vilhelmprytz/pterodactyl-installer#55]
I would suggest looking into the download of `apt-transport-https` since I'm almost confident that Ubuntu versions higher then Xenial Xerus or identical to it have https support for aptitude by default, same for Debian higher then stretch, though not identical.

If what I said made sense :P 

This website probably explains it better lol https://whydoesaptnotusehttps.com/

I would have opened a pr for this but I'm way too lazy, sorry.

Possible solution:

Checking if aptitude version is lower then 1.5, if so, install the package. If not, don't :)

Daniel

**Comment by vilhelmprytz** [comment]
As the website you linked stated, there are really no disadvantages of using HTTPS with `apt`. Yes, it does not improve security really since `apt` already has other mechanisms for verification but then it doesn't worsen the security either. I don't know why you would not use it (also Docker recommends it).

And regarding the fact that is it pre-installed since xenial: it might very well be; some of the lines in the `ubuntu16_dep` function in the script have not been modified for over two years. Again, it doesn't hurt the script to make sure it is installed. If you can find proof of the fact that it is pre-installed, I'd be happy to accept a pull request :smile: 

Cheers

**Comment by danielnaaman** [comment]
Sorry for being unclear, it is necessary! I find security very important. My meaning is that this package is no longer needed, since Aptitude (v1.5+) supports secured connections by default.

No external package required. You can test it relatively easily, just spin up a server for a second and try to change your mirrors to HTTPS ones without download anything, you can also make sure that the `apt-transport-https` package is not installed before you do so.

If you wish me to send a video of me doing so, I'd love to do that.

Again, it's not really important whatsoever, but in some cases it's a bit unnecessary.

**Comment by vilhelmprytz** [comment]
Perhaps this is the case for Ubuntu but at least previously (this might have changed), the HTTPS feature was set aside as an extension, I specifically remember having to install it on Debian.

The reasoning for installing it in the first place is because I have tried to stick to the installation instructions given by the authors of the software; when possible. Hence you can see that [the Docker installation guide for Ubuntu](https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository) does indeed install `apt-transport-https`.

**Comment by danielnaaman** [comment]
I see, then you are right. Sorry for the confusion! :D
