### ISSUE TITLE
Add support for Debian 10

### ISSUE THREAD

**Issue by VilhelmPrytz** [VilhelmPrytz/pterodactyl-installer#7]
Not yet listed as officially supported by the Pterodactyl team, but should be easy to implement.

**Comment by VilhelmPrytz** [comment]
I've tried adding Debian 10 support for daemon installations but I keep getting "unexpected file size" when communicating with Docker repository. Will require further investigation.

**Comment by Hoerli1337** [comment]
I am reopening the problem to help other users.
Currently the installation of Deamon on Debian 10 / Ubuntu 19.X does not work.
"npm install --only=production always" runs into several errors.
nodejs -v -> v13.9.0
npm -v -> 6.13.7

Debian 9 with nodejs 10.X however works.
The installation script works perfectly, the problem is clearly due to pterodactyl.

:)

**Comment by VilhelmPrytz** [comment]
They do run into issues, I noticed this as well, but I think it works anyway? Have you tried staring the daemon with `npm start`?

**Comment by Hoerli1337** [comment]
Yes i try it with Debian 10 / Ubuntu 19.X and nodejs 10, 12 and 13. All Fail.
I can't start the system then, because a lot of data seems to be missing.
I have tested VMware directly on my PC, as well as on a VPS hoster with LXC.
(Docker runs there with LXC)

Only Debian 9 with nodejs 10 works fine.

**Comment by VilhelmPrytz** [comment]
This issue was opened for adding support for Debian 10, could you open this as a separate issue (with logs as well)?

I'm closing this again.
