### ISSUE TITLE
NPM (Port 8080) does not start after a reboot

### ISSUE THREAD

**Issue by TUBEOF** [vilhelmprytz/pterodactyl-installer#93]
**Describe the bug**
After a reboot the server daemon is not online in the panel. Its caused by the pterosftp.service

**To Reproduce**
Steps to reproduce the behaviour:
1. Install it
2. Restart the rootserver
3. Run "lsof -i", there you can see only the SFTP Server is started. Not 8080

**To fix it:**
Run the following commands via SSH on the daemon root:
"systemctl stop pterosftp.service"
"systemctl disable pterosftp.service"
"reboot"

SFTP Server and NPM should start without any problems and the node should be displayed as online in the panel.

**OS (please complete the following information):**
 - OS: Debian 10
 - Installation: Daemon

**Additional context**

**Comment by Linux123123** [comment]
No you are wrong. You need to disable the internal `SFTP` server of the daemon in the `core.json`. Otherwise the daemon will error out because port 2022 is already in use. This also only happens if you choose external `SFTP` server during install. Next time before opening an issue check [our official discord server](https://discord.gg/2zMdudJ) or the official pterodactyl documentation.

**Comment by vilhelmprytz** [comment]
I believe @Linux123123 is correct here. Feel free to join the Discord for support with the script. Closing this. Re-open if this is incorrect! :+1:
